server:
  port: 9999

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/xdb
  redis:
    port: 6379
    host: 192.168.200.135
    password: 123456

logging:
  level:
    com.lantu: info

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  #全局进行逻辑删除的字段(它会在删除数据后，若再进行相关操作，都会带上deleted=0的语句)
      logic-not-delete-value: 0    #逻辑已删除的值默认为0
      logic-delete-value: 1        #逻辑为删除的默认值为1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


